Template/Controllers/StudentController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Template.Business.EnrollementBusiness;
using Template.Business.FormerSchoolBusiness;
using Template.Business.GuardianBusiness;
using Template.Business.StudentBusiness;
using Template.Business.SubjectBusiness;
using Template.Model.StudentModels;
using Template.Model.SubjectModels;
using Template.Service.StudentService;

namespace Template.Controllers
{
    [Authorize]
    public class StudentController : Controller
    {
        // GET: StudentController
        private readonly IStudentBusinessLogic _studentbusiness;
        private readonly ISubjectbusinessLogic _subjectbusiness;
        private readonly IGuardianBusinessLogic _guardianbusiness;
        private readonly ISchoolBusinessLogic _schoolbusiness;
        private readonly IEnrollementBusinessLogic _enrollementbusiness;
        public StudentController(IStudentBusinessLogic studentbusiness, ISubjectbusinessLogic subjectbusiness,
            IGuardianBusinessLogic guardianbusiness, ISchoolBusinessLogic schoolbusiness, IEnrollementBusinessLogic enrollementbusiness)
        {
            _studentbusiness = studentbusiness;
            _subjectbusiness = subjectbusiness;
            _guardianbusiness = guardianbusiness;
            _schoolbusiness = schoolbusiness;
            _enrollementbusiness = enrollementbusiness;
    }
        public async Task<ActionResult>Index(string Search_Data)
        { 
            var students = await _studentbusiness.AllStudentsAsync();
            if(Search_Data!=null)
            {
                students = students.Where(stu => stu.FirstName.ToLower().Contains(Search_Data.ToUpper())
                 || stu.Identity.ToUpper().Contains(Search_Data.ToUpper()) || stu.Surname.ToUpper().Contains(Search_Data.ToUpper())).ToList();
            }
            return View(students.ToList());
        }
        public async Task<ActionResult> Create()
        {
            var studentmodel = new StudentModel
            {
                Subjects = await _subjectbusiness.AllSubjects(),
            };
            return View(studentmodel);
        }
        // POST: StudentController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(StudentModel model)
        {
            model.Subjects = model.Subjects;
            try
            {
                if (ValidateSubjects(model.Subjects) && ! ModelState.IsValid)
                {
                    model.Subjects = model.Subjects;
                    ModelState.AddModelError("", "Student can only register for 3 or less subjects");               
                    return View(model);
                }
                var guard_identity = await _guardianbusiness.InsertGuardianAsync(model);
                var schoolid =Convert.ToInt16(await _schoolbusiness.InsertSchoolAsync(model));
                var identity=await _studentbusiness.InsertStudentAsync(model,guard_identity,schoolid);
                await _enrollementbusiness.InsertChosenSubjects(model.Subjects, identity);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                model.Subjects = model.Subjects;
                return View();
            }
        }
        public async Task<ActionResult> StudentProfile(string Identity)
        {
            var profife = await _studentbusiness.GetStudentByIdentityAsync(Identity);
            return View(profife);
        }
        private bool ValidateSubjects(List<SubjectViewModel> list)
        {
            if(list.Where(p => p.CheckboxAnswer.Equals(true)).Count()>3)
            {
                return true;
            }
            return false;
        }
    }
}

Template/Controllers/SubjectController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Template.Business.SubjectBusiness;
using Template.Model.SubjectModels;

namespace Template.Controllers
{
    [Authorize]
    public class SubjectController : Controller
    {
        private readonly ISubjectbusinessLogic _subjectbusiness;
        public SubjectController(ISubjectbusinessLogic subjectbusiness)
        {
            _subjectbusiness = subjectbusiness;
        }
        public async Task<ActionResult>Index()
        {
            return View(await _subjectbusiness.AllSubjects());
        }
        public async Task<ActionResult> Create()
        {
            return View();
        }
        // POST: SubjectController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task< ActionResult> Create(SubjectModel model)
        {
            try
            {
                if(!ModelState.IsValid)
                {
                    ModelState.AddModelError("", "make sure all fields are filled");
                    return View(model);
                }
                await _subjectbusiness.InsertSubject(model);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Template/Views/Shared/_Admin.cshtml
<!doctype html>
<html lang="en">

<head>
    <title>Dashboard |Matric Excellence</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <!-- VENDOR CSS -->
    <link rel="stylesheet" href="~/assets/vendor/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/assets/vendor/font-awesome/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/assets/vendor/linearicons/style.css">
    <link rel="stylesheet" href="~/assets/vendor/chartist/css/chartist-custom.css">
    <!-- MAIN CSS -->
    <link rel="stylesheet" href="~/assets/css/main.css">
    <!-- FOR DEMO PURPOSES ONLY. You should remove this in your project -->
    <link rel="stylesheet" href="~/assets/css/demo.css">
    <!-- GOOGLE FONTS -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700" rel="stylesheet">
    <!-- ICONS -->
    <link rel="apple-touch-icon" sizes="76x76" href="~/assets/img/apple-icon.png">
    <link rel="icon" type="image/png" sizes="96x96" href="~/assets/img/favicon.png">
</head>

<body>
    <!-- WRAPPER -->
    <div id="wrapper">
        <!-- NAVBAR -->
        <nav class="navbar navbar-default navbar-fixed-top">
            <div class="brand">
                Admin
            </div>
            <div class="container-fluid">
                <div class="navbar-btn">
                    <button type="button" class="btn-toggle-fullwidth"><i class="lnr lnr-arrow-left-circle"></i></button>
                </div>
                <div id="navbar-menu">
                    <partial name="_LoginPartial">
                </div>
            </div>
        </nav>
        <!-- END NAVBAR -->
        <!-- LEFT SIDEBAR -->
        <div id="sidebar-nav" class="sidebar">
            <div class="sidebar-scroll">
                <nav>
                    <ul class="nav">
                        <li><a href="@Url.Action("Index", "Student")" class="active"><i class="lnr lnr-home"></i>  <span>Dashboard</span></a></li>
                        <li><a href="@Url.Action("Index", "Student")" class=""><i class="lnr lnr-users"></i>  <span>Students</span></a></li>
                        <li><a href="@Url.Action("Index", "Subject")" class=""><i class="lnr lnr-book"></i> <span>Subjects</span></a></li>
                    </ul>
                </nav>
            </div>
        </div>
        <!-- END LEFT SIDEBAR -->
        <!-- MAIN -->
        <div class="main " style="background-color:aquamarine">
            <!-- MAIN CONTENT -->
            <div class="main-content">
                <div class="container-fluid">
                    <!-- OVERVIEW -->
                    <div class="panel panel-headline">
                        @RenderBody()
                    </div>
                    <!-- END OVERVIEW -->
                </div>
            </div>
            <!-- END MAIN CONTENT -->
        </div>
        <!-- END MAIN -->
        <div class="clearfix"></div>
        <footer>
            <div class="container-fluid">
                <p class="copyright">&copy; 2021 <a href="https://www.themeineed.com" target="_blank">MatricExcellence</a>. All Rights Reserved.</p>
            </div>
        </footer>
    </div>
    <!-- END WRAPPER -->
    <!-- Javascript -->
    <script src="~/assets/vendor/jquery/jquery.min.js"></script>
    <script src="~/assets/vendor/bootstrap/js/bootstrap.min.js"></script>
    <script src="~/assets/vendor/jquery-slimscroll/jquery.slimscroll.min.js"></script>
    <script src="~/assets/vendor/jquery.easy-pie-chart/jquery.easypiechart.min.js"></script>
    <script src="~/assets/vendor/chartist/js/chartist.min.js"></script>
    <script src="~/assets/scripts/klorofil-common.js"></script>
    <script src="~/assets/scripts/Autocomplete.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>

Template/Views/Shared/_First.cshtml
<!doctype html>
<html lang="en" class="fullscreen-bg">

<head>
    <title>Login | Matric Excellence</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <!-- VENDOR CSS -->
    <link rel="stylesheet" href="~/assets/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/assets/vendor/font-awesome/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/assets/vendor/linearicons/style.css">
    <!-- MAIN CSS -->
    <link rel="stylesheet" href="~/assets/css/main.css">
    <!-- FOR DEMO PURPOSES ONLY. You should remove this in your project -->
    <link rel="stylesheet" href="~/assets/css/demo.css">
    <!-- GOOGLE FONTS -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700" rel="stylesheet">
    <!-- ICONS -->
    <link rel="apple-touch-icon" sizes="76x76" href="~/assets/img/apple-icon.png">
    <link rel="icon" type="image/png" sizes="96x96" href="assets/img/favicon.png">
</head>
<body>
    <div id="wrapper">
        <div class="vertical-align-wrap">
            <div class="vertical-align-middle">
                <div class="auth-box ">
                    <div class="left">
                        @RenderBody()
                    </div>
                    <div class="right">
                        <div class="overlay"></div>
                        <div class="content text">
                            <h1 class="heading">Matric Excellence</h1>
                        </div>
                    </div>
                    <div class="clearfix"></div>
                </div>
            </div>
        </div>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Template/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Template</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Template</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Template - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>