Template/Controllers/PaymentController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Template.Business.PaymentBusiness;
using Template.Business.StudentBusiness;
using Template.Model.PaymentModels;
using Template.Model.StudentModels;

namespace Template.Controllers
{
    [Authorize]
    public class PaymentController : Controller
    {
        private readonly IPaymentBusinessLogic _paymentbusiness;
        private readonly IStudentBusinessLogic _studentsbusiness;
        public PaymentController(IPaymentBusinessLogic paymentbusiness, IStudentBusinessLogic studentsbusiness)
        {
            _paymentbusiness = paymentbusiness;
            _studentsbusiness = studentsbusiness;


        }
        // GET: PaymentController/Create
        public ActionResult Create(string Identity)
        {
            var payemnt = new PaymentModel
            {
                StudentIdentity = Identity
            };
            return View(payemnt);
        }
        // POST: PaymentController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(PaymentModel model)
        {
            try
            {
                if(!await _paymentbusiness.AddPayment(model))
                {
                    ModelState.AddModelError("", "Student Identity not found");
                    return View(model);
                }
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
        public async Task<IActionResult> Students(string term)
        {
            List<StudentViewModel> list = await _studentsbusiness.AllStudentsAsync();
            return Json(list.Where(p=>p.FirstName.StartsWith(term, StringComparison.CurrentCultureIgnoreCase)).ToArray());
        }

    }
}

Template/Controllers/StudentController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Template.Business.EnrollementBusiness;
using Template.Business.FormerSchoolBusiness;
using Template.Business.GuardianBusiness;
using Template.Business.StudentBusiness;
using Template.Business.SubjectBusiness;
using Template.Model.StudentModels;
using Template.Model.SubjectModels;
using Template.Service.StudentService;

namespace Template.Controllers
{
    [Authorize]
    public class StudentController : Controller
    {
        // GET: StudentController
        private readonly IStudentBusinessLogic _studentbusiness;
        private readonly ISubjectbusinessLogic _subjectbusiness;
        private readonly IGuardianBusinessLogic _guardianbusiness;
        private readonly ISchoolBusinessLogic _schoolbusiness;
        private readonly IEnrollementBusinessLogic _enrollementbusiness;
        public StudentController(IStudentBusinessLogic studentbusiness, ISubjectbusinessLogic subjectbusiness,
            IGuardianBusinessLogic guardianbusiness, ISchoolBusinessLogic schoolbusiness, IEnrollementBusinessLogic enrollementbusiness)
        {
            _studentbusiness = studentbusiness;
            _subjectbusiness = subjectbusiness;
            _guardianbusiness = guardianbusiness;
            _schoolbusiness = schoolbusiness;
            _enrollementbusiness = enrollementbusiness;
    }
        public async Task<ActionResult>Index(string Search_Data)
        { 
            var students = await _studentbusiness.AllStudentsAsync();
            if(Search_Data!=null)
            {
                students = students.Where(stu => stu.FirstName.ToLower().Contains(Search_Data.ToUpper())
                 || stu.Identity.ToUpper().Contains(Search_Data.ToUpper()) || stu.Surname.ToUpper().Contains(Search_Data.ToUpper())).ToList();
            }
            return View(students.ToList());
        }
        public async Task<ActionResult> Create()
        {
            var studentmodel = new StudentModel
            {
                Subjects = await _subjectbusiness.AllSubjects(),
            };
            return View(studentmodel);
        }
        // POST: StudentController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(StudentModel model)
        {
            model.Subjects = model.Subjects;
            try
            {
                if (ValidateSubjects(model.Subjects) && ! ModelState.IsValid)
                {
                    model.Subjects = model.Subjects;
                    ModelState.AddModelError("", "Student can only register for 3 or less subjects");               
                    return View(model);
                }
                var guard_identity = await _guardianbusiness.InsertGuardianAsync(model);
                var schoolid =Convert.ToInt16(await _schoolbusiness.InsertSchoolAsync(model));
                var identity=await _studentbusiness.InsertStudentAsync(model,guard_identity,schoolid);
                await _enrollementbusiness.InsertChosenSubjects(model.Subjects, identity);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                model.Subjects = model.Subjects;
                return View();
            }
        }
        public async Task<ActionResult> StudentProfile(string Identity)
        {
            var profife = await _studentbusiness.GetStudentByIdentityAsync(Identity);
            return View(profife);
        }
        private bool ValidateSubjects(List<SubjectViewModel> list)
        {
            if(list.Where(p => p.CheckboxAnswer.Equals(true)).Count()>3)
            {
                return true;
            }
            return false;
        }
    }
}

Template/Views/Student/Create.cshtml
@using Template.Model.StudentModels
@model Template.Model.StudentModels.StudentModel

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Admin.cshtml";
}
<div class="panel-body">
    <div class="panel-heading"><h2>Add Student</h2></div>
    <div class="row">
        <div class="panel-heading">
            <h4 class="heading-1"> <span>Student Information</span> </h4>
        </div>
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group row">
                <div class="col-sm-1">
                    <label asp-for="Title" class="control-label"></label>
                    <select asp-for="Title" class="form-control" asp-items="Html.GetEnumSelectList<TittleEnum>()">
                        <option>Select Tittle ...</option>
                    </select>
                    <span asp-validation-for="Title" class="text-danger"></span>
                </div>
                <div class="col-sm-3">
                    <label asp-for="FirstName" class="control-label"></label>
                    <input asp-for="FirstName" class="form-control" />
                    <span asp-validation-for="FirstName" class="text-danger"></span>
                </div>
                <div class="col-sm-3">
                    <label asp-for="Surname" class="control-label"></label>
                    <input asp-for="Surname" class="form-control" />
                    <span asp-validation-for="Surname" class="text-danger"></span>
                </div>
                <div class="col-sm-4">
                    <label asp-for="Identity" class="control-label"></label>
                    <input asp-for="Identity" class="form-control" />
                    <span asp-validation-for="Identity" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group row">
                <div class="col-sm-3">
                    <label asp-for="Nationality" class="control-label"></label>
                    <input asp-for="Nationality" class="form-control" />
                    <span asp-validation-for="Nationality" class="text-danger"></span>
                </div>
                <div class="col-sm-3">
                    <label asp-for="CellNumber" class="control-label"></label>
                    <input asp-for="CellNumber" class="form-control" />
                    <span asp-validation-for="CellNumber" class="text-danger"></span>
                </div>
                <div class="col-sm-4">
                    <label asp-for="Email" class="control-label"></label>
                    <input asp-for="Email" class="form-control" />
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-sm-4">
                    <label asp-for="Address" class="control-label"></label>
                    <textarea asp-for="Address" class="form-control mb-3" rows="3" placeholder="Address"></textarea>
                    <span asp-validation-for="Address" class="text-danger"></span>
                </div>
                <div class="col-sm-2 col-xs-2">
                    <label asp-for="Code" class="control-label"></label>
                    <input asp-for="Code" class="form-control col-xs-2" />
                    <span asp-validation-for="Code" class="text-danger"></span>
                </div>
                <div class="col-sm-4">
                    <label asp-for="TelephoneNumber" class="control-label"></label>
                    <input asp-for="TelephoneNumber" class="form-control" />
                    <span asp-validation-for="TelephoneNumber" class="text-danger"></span>
                </div>
            </div>
            <div class="panel-heading">
                <h4 class="heading-1"> <span>Guardian Information</span> </h4>
            </div>
            <div class="form-group row">
                <div class="col-sm-4">
                    <label asp-for="Guardian_FirstName" class="control-label"></label>
                    <input asp-for="Guardian_FirstName" class="form-control" />
                    <span asp-validation-for="Guardian_FirstName" class="text-danger"></span>
                </div>
                <div class="col-sm-4">
                    <label asp-for="Guardian_Surname" class="control-label"></label>
                    <input asp-for="Guardian_Surname" class="form-control" />
                    <span asp-validation-for="Guardian_Surname" class="text-danger"></span>
                </div>
                <div class="col-sm-4">
                    <label asp-for="Guardian_Identity" class="control-label"></label>
                    <input asp-for="Guardian_Identity" class="form-control" />
                    <span asp-validation-for="Guardian_Identity" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-sm-4">
                    <label asp-for="Guardian_Address" class="control-label"></label>
                    <textarea asp-for="Guardian_Address" class="form-control mb-3" rows="3" placeholder="Address"></textarea>
                    <span asp-validation-for="Guardian_Address" class="text-danger"></span>
                </div>
                <div class="col-sm-4">
                    <label asp-for="Relationship" class="control-label"></label>
                    <input asp-for="Relationship" class="form-control" />
                    <span asp-validation-for="Relationship" class="text-danger"></span>
                </div>
                <div class="col-sm-1">
                    <label asp-for="Guardian_Title" class="control-label"></label>
                    <select asp-for="Guardian_Title" class="form-control" asp-items="Html.GetEnumSelectList<TittleEnum>()">
                        <option>Select Tittle ...</option>
                    </select>
                    <span asp-validation-for="Guardian_Title" class="text-danger"></span>
                </div>

            </div>
            <div class="form-group row">
                <div class="col-sm-2 col-xs-2">
                    <label asp-for="Guardian_Address_Code" class="control-label"></label>
                    <input asp-for="Guardian_Address_Code" class="form-control col-xs-2" />
                    <span asp-validation-for="Guardian_Address_Code" class="text-danger"></span>
                </div>
                <div class="col-sm-4">
                    <label asp-for="Occupation" class="control-label"></label>
                    <input asp-for="Occupation" class="form-control" />
                    <span asp-validation-for="Occupation" class="text-danger"></span>
                </div>

                <div class="col-sm-4">
                    <label asp-for="Guardian_CellPhone" class="control-label"></label>
                    <input asp-for="Guardian_CellPhone" class="form-control" />
                    <span asp-validation-for="Guardian_CellPhone" class="text-danger"></span>
                </div>
            </div>
            <div class="panel-heading">
                <h4 class="heading-1"> <span>Former School</span> </h4>
            </div>
            <div class="form-group row">
                <div class="col-sm-2 col-xs-2">
                    <label asp-for="School_Name" class="control-label"></label>
                    <input asp-for="School_Name" class="form-control col-xs-2" />
                    <span asp-validation-for="School_Name" class="text-danger"></span>
                </div>
                <div class="col-sm-4">
                    <label asp-for="School_Center" class="control-label"></label>
                    <input asp-for="School_Center" class="form-control" />
                    <span asp-validation-for="School_Center" class="text-danger"></span>
                </div>

                <div class="col-sm-4">
                    <label asp-for="School_City_Town" class="control-label"></label>
                    <input asp-for="School_City_Town" class="form-control" />
                    <span asp-validation-for="School_City_Town" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-sm-4">
                    <label asp-for="School_ContactNumber" class="control-label"></label>
                    <input asp-for="School_ContactNumber" class="form-control" />
                    <span asp-validation-for="School_ContactNumber" class="text-danger"></span>
                </div>
            </div>


            <div class="panel-heading">
                <h4 class="heading-1 text-warning"> <span>Subjects Choices</span> </h4>
            </div>


            <div class="form-group row">
                <div class="col-md-offset-2 col-md-10 input-validation-error">
     
                        @for (int i = 0; i < Model.Subjects.Count(); i++)
                        {
                            <div class="col-sm-2">
                                <input asp-for="@Model.Subjects[i].CheckboxAnswer" type="checkbox" class = "hobbycls"/>
                                <label asp-for="@Model.Subjects[i].Id">@Model.Subjects[i].Name</label>
                                <input asp-for="@Model.Subjects[i].Id" type="hidden" />
                                <input asp-for="@Model.Subjects[i].Name" type="hidden" />
                                <span asp-validation-for="Subjects" class="text-danger"></span>
                                <br />
                            </div>
                        }
                        <span id="Hobbies-error" class="field-validation-error">
                            <span>Select any hobbies.</span>
                        </span>
                    
                </div>
                    <div>
                        <hr />
                    </div>
                    <span asp-validation-for="Subjects" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Register Student" class="btn btn-primary btn-lg" />
                </div>

</form>

    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}


    <script type="text/javascript">
        var declarationsError = $('#Hobbies-error');
        $('form').submit(function () {
            if ($(".hobbycls:checkbox:checked").length > 0) {
                declarationsError.hide();
                return true;
            } else {
                declarationsError.show();
                return false;
            }
        });

        $('.hobbycls').change(function () {
            if ($(this).is(':checked')) {
                declarationsError.hide(); // hide error message
            }
        });
    </script>
}
<style>
    .heading-1 {
        position: relative;
        text-align: center
    }

        .heading-1:before {
            content: "";
            display: block;
            border-top: solid 2px #bebebe;
            width: 100%;
            height: 2px;
            position: absolute;
            top: 50%;
            z-index: 0;
        }

        .heading-1 span {
            background: #fff;
            padding: 0 10px;
            position: relative;
            z-index: 1;
        }
</style>

Template/Views/Student/Index.cshtml
@model IEnumerable<Template.Model.StudentModels.StudentViewModel>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Admin.cshtml";
}
<div class="panel-body">
    <div class="row">
        <div class="panel">
            <div class="panel-heading">

                @using (Html.BeginForm())
                {
                    <div class="row">
                        <div class="form-group row">
                            <div class="col-sm-2"><b>Search Identity</b></div>
                            <div class="col-sm-4">@Html.TextBox("Search_Data", ViewBag.FilterValue as string, new { @class = "form-control col-sm-3" })</div>
                            <div class="col-sm-4"> <input type="submit" value="Search Student" class="btn btn-info" />  </div>
                        </div>

                    </div>
                }
                <div class="right">
                    <button type="button" class="btn-toggle-collapse"><i class="lnr lnr-chevron-up"></i></button>
                    <button type="button" class="btn-remove"><i class="lnr lnr-cross"></i></button>
                </div>
            </div>

                                <div class="col-lg-9">
                                    <div class="table-responsive ">
                                        <table class="table table-borderless table-striped table-earning">
                                            <thead>
                                                <tr>
                                                    <th>
                                                        First Name
                                                    </th>
                                                    <th>Surname</th>
                                                    <th>
                                                        Enrollment Date
                                                    </th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                @foreach (var item in Model)
                                                {
                                                    <tr>
                                                        <td>
                                                            <a href="@Url.Action("StudentProfile","Student",new {Identity=item.Identity })">@item.FirstName</a>

                                                        </td>
                                                        <td>@item.Surname</td>
                                                        <td>@item.CellNumber</td>
                                                        <td>@item.DateCreated</td>
                                                    </tr>
                                                }
                                            </tbody>
                                        </table>
                                    </div>
                                    <div class="panel-footer">
                                        <div class="row">
                                            <div class="col-md-6 text-right"><a asp-action="Create" class="btn btn-success">Add New Student</a></div>
                                        </div>
                                    </div>
                                </div>
</div>
            </div>
    </div>

Template/Views/Student/StudentProfile.cshtml
@model Template.Model.StudentModels.StudentViewModel

@{
    ViewData["Title"] = "StudentProfile";
    Layout = "~/Views/Shared/_Admin.cshtml";
}
<div class="panel-body">
    <div class="main-content">
        <div class="container-fluid">
            <div class="panel panel-profile">
                <div class="clearfix">
                    <div class="profile-left">
                        <div class="profile-header">
                            <div class="overlay"></div>
                            <div class="profile-main">
                                <h3 class="name">@Model.FirstName</h3>
                                <span class="online-status status-available">Active</span>
                            </div>
                        </div>



                        <div class="profile-detail">
                            <div class="profile-info">
                                <h4 class="heading">Student Info</h4>
                                <ul class="list-unstyled list-justify">
                                    <li>Identity <span>@Model.Identity</span></li>
                                    <li>Mobile <span>@Model.CellNumber</span></li>
                                    <li>Email <span>@Model.Email</span></li>
                                </ul>
                            </div>
                            <div class="profile-info">
                                <h4 class="heading">Former School</h4>
                                <ul class="list-unstyled list-justify">
                                    <li>Name <span>@Model.School.Name</span></li>
                                    <li>Center <span>@Model.School.Center</span></li>
                                    <li>Contact Number <span>@Model.School.ContactNumber</span></li>
                                </ul>
                            </div>
                            <div class="profile-info card">
                                <h4 class="heading">Guardian Info</h4>
                                <ul class="list-unstyled list-justify">
                                    <li>Name <span>@Model.Parent.FirstName</span></li>
                                    <li>Surname <span>@Model.Parent.LastName</span></li>
                                    <li>Relationship <span>@Model.Parent.Relationship</span></li>
                                    <li>Contact Number <span>@Model.Parent.CellPhone</a></span></li>
                                </ul>
                            </div>
                        </div>
                        <!-- END PROFILE DETAIL -->
                    </div>
                    <!-- END LEFT COLUMN -->
                    <!-- RIGHT COLUMN -->
                    <div class="profile-right">
                        <h4 class="heading">Student Payments</h4>
                        <!-- AWARDS -->
                        <div class="awards">
                            <div class="row">
                                <div class="panel-body no-padding">
                                    <table class="table table-striped">
                                        <thead>
                                            <tr>
                                                <th>Month</th>
                                                <th>Amount</th>
                                                <th>Date Created</th>
                                                <th>Status</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach (var item in Model.Payments)
                                            {

                                                <tr>
                                                    <td>@item.Month</td>
                                                    <td>@item.Amount</td>
                                                    <td>@item.DateCreated</td>
                                                    <td><span class="label label-success">Approved</span></td>
                                                </tr>
                                            }
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                            <div class="text-center"><a href="@Url.Action("Create","Payment",new {Identity=Model.Identity })" class="btn btn-primary btn-lg">New Payment</a></div>
                        </div>
                        <div class="custom-tabs-line tabs-line-bottom left-aligned">
                            <ul class="nav" role="tablist">
                                <li class="active"><a href="#tab-bottom-left1" role="tab" data-toggle="tab">Students Subjects</a></li>
                            </ul>
                        </div>
                        <div class="tab-content">

                            <div class="table-responsive">
                                <table class="table project-table">
                                    <thead>
                                        <tr>
                                            <th>ID</th>
                                            <th>Name</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach (var item in Model.Enrollements)
                                        {

                                            <tr>
                                                <td>@item.Id</td>
                                                <td>@item.Name</td>
                                            </tr>
                                        }
                                    </tbody>
                                </table>
                            </div>


                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
   </div>